spring.datasource.url=jdbc:postgresql://neondb_owner:npg_UVEPZRJ0qXG3@ep-dry-night-alpl4fje-pooler.c-3.eu-central-1.aws.neon.tech/shop?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=YourSecretPasswordGivenByNeon
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

